adminpage/urls.py
from django.conf.urls import url
from . import views

app_name='adminpage'

urlpatterns = [
    url(r'^$', views.admin_index, name='admin_index'),
    url(r'^tilbakemeldinger/$',views.tilbakemeldinger, name="tilbakemeldinger"),
    url(r'^tilbakemeldinger/(?P<subject_pk>[A-Za-z0-9]+)/$', views.chapters, name="chapters"),
    url(r'^tilbakemeldinger/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.chapter_feedback, name="chapter_feedback"),

    url(r'^subjects/$', views.subject_overview, name='subject_overview'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/$', views.chapter_overview, name='chapter_overview'),
    url(r'^subjects/new_subject/$', views.new_subject, name='new_subject'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/change_chapter/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.change_chapter, name='change_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/new_chapter/$', views.new_chapter, name='new_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/delete/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.delete_chapter, name='delete_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/delete/$', views.delete_subject, name='delete_subject'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.exercise_overview,name='exercise_overview'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/new_exercise/$', views.new_exercise,
        name='new_exercise'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/(?P<exercise_pk>[A-Za-z0-9]+)/delete/$', views.delete_exercise,
        name='delete_exercise'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/change_exercise/(?P<exercise_pk>[A-Za-z0-9]+)/$', views.change_exercise,
        name='change_exercise'),

]

main/urls.py
from django.conf.urls import url
from . import views

app_name='main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^userregister/$', views.userregister, name='userregister'),
    url(r'^professorregister/$', views.professorregister, name='professorregister'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_subject/(?P<subject_pk>[A-Za-z0-9]+)$', views.add_subject, name='add_subject'),

]

nysil/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
    url(r'^my_subjects/', include('my_subjects.urls')),
    url(r'^adminpage/', include('adminpage.urls')),
    url(r'^progress/', include('progress.urls')),
    url(r'^adminpage/statistics/', include('stats.urls')),

]

stats/urls.py
from django.conf.urls import url
from . import views

app_name='stats'

urlpatterns = [
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/graph/(?P<exercise_pk>[A-Za-z0-9]+)/$', views.exercise_bargraph, name='exercise_bargraph'),
    url(r'^$', views.statistics_index, name='statistics_index'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/$', views.statistics_subject, name='statistics_subject'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/overview/$', views.subject_overview, name='subject_overview'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/highscore/$', views.subject_highscore, name='subject_highscore'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/chapters/$', views.subject_chapters, name='subject_chapters'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/exercises/$', views.subject_exercise, name='subject_exercise'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/chapter_plot/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.chapter_plot, name='chapter_plot'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/graph/$', views.subject_pie_graph, name='subject_pie_graph'),

]

stats/models.py
from django.db import models

# Create your models here.

stats/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from main.models import Subject, StudentConnectSubject, Exercise_Page, StudentConnectExercise, Chapter

# THE FIRST LINES IN EVERY VIEW IS A CHECK TO SEE THAT A USER HAS LOGGED IN, THIS IS DONE TO PROVIDE THAT USERS THAT
# ARE NOT AUTHENTICATED CAN ACCESS IT.


def statistics_index(request):
    if not user_authenticated(request.user):
        return HttpResponseRedirect(reverse('main:index'))

    context = {'subjects': Subject.objects.all()}
    return render(request, 'stats/statistics_index.html',context)

def statistics_subject(request, subject_pk):
    if not user_authenticated(request.user):
        return HttpResponseRedirect(reverse('main:index'))

    context = {'subjects': Subject.objects.all(), 'subject': Subject.objects.get(pk=subject_pk)}
    return render(request, 'stats/statistics_subject.html', context)

def subject_overview(request, subject_pk):
    subject = Subject.objects.get(pk=subject_pk)
    num_students = get_number_of_students(subject)
    context = {'subjects': Subject.objects.all(), 'subject': subject, 'num_students': num_students}
    return render(request, "stats/subject_overview.html", context)


def subject_highscore(request, subject_pk):
    if not user_authenticated(request.user):
        return HttpResponseRedirect(reverse('main:index'))

    subject = Subject.objects.get(pk=subject_pk)
    # highscore_info on the form [[rank,connection].....[rank,connection]]
    highscore_info = fix_highscore_info(subject)
    context = {'subjects': Subject.objects.all(), 'subject': subject, 'highscore_info': highscore_info}
    return render(request, "stats/subject_highscore.html", context)


def subject_chapters(request, subject_pk):
    if not user_authenticated(request.user):
        return HttpResponseRedirect(reverse('main:index'))

    subject = Subject.objects.get(pk=subject_pk)
    context = {'subjects': Subject.objects.all(), 'subject': subject}
    return render(request,'stats/subject_chapters.html', context)


def subject_exercise(request, subject_pk):
    if not user_authenticated(request.user):
        return HttpResponseRedirect(reverse('main:index'))

    subject = Subject.objects.get(pk=subject_pk)
    context = {'subjects': Subject.objects.all(), 'subject': subject}
    return render(request, 'stats/subject_exercise.html', context)

# view that creates info around a chapter and render this info
def chapter_plot(request, subject_pk, chapter_pk):
    if not user_authenticated(request.user):
        return HttpResponseRedirect(reverse('main:index'))

    subject = Subject.objects.get(pk=subject_pk)
    chapter = Chapter.objects.get(pk=chapter_pk)
    info = create_chapter_graph(chapter)
    length = len(info)
    context = {'chapter': chapter, 'subjects': Subject.objects.all(), 'subject': subject, 'info': info, 'length': length}

    return render(request, 'stats/chapter_plot.html', context)


def exercise_bargraph(request, subject_pk, exercise_pk):
    if not user_authenticated(request.user):
        return HttpResponseRedirect(reverse('main:index'))

    exercise = Exercise_Page.objects.get(pk=exercise_pk)
    means = create_means(exercise)

    context = {'exercise':exercise, 'subjects': Subject.objects.all(), 'means': means, 'subject': Subject.objects.get(pk=subject_pk)}
    return render(request, 'stats/exercise_bargraph.html', context)

def subject_pie_graph(request,subject_pk):
    if not user_authenticated(request.user):
        return HttpResponseRedirect(reverse('main:index'))

    subject = Subject.objects.get(pk=subject_pk)
    graph_values = create_subject_graph_values(subject)

    context = {'subjects': Subject.objects.all(), 'values': graph_values , 'subject': subject}
    return render(request, 'stats/subject_graph.html', context)

# --------------------- HELP - METHODS ---------------------------

def get_number_of_students(subject):
    return StudentConnectSubject.objects.filter(subject=subject).count()

# set the highscore_info on a special format
def fix_highscore_info(subject):
    info = []
    students_in_subject_conn = StudentConnectSubject.objects.filter(subject=subject).order_by('-points')
    rank=1
    max_points = get_max_points(subject)
    for student_conn in students_in_subject_conn:
        percent = (str(round(student_conn.points*100/max_points,1)) if max_points > 0 else "0") + " %"
        info.append([rank, student_conn, percent])
        rank += 1
    return info

# max_points to a subject
def get_max_points(subject):
    chapters = subject.chapter_set.all()
    points = 0
    for chapter in chapters:
        exercises = chapter.exercise_page_set.all()
        for exercise in exercises:
            points += exercise.easy_points + exercise.medium_points + exercise.hard_points
    return points



def create_means(exercise):
    conns = StudentConnectExercise.objects.filter(exercise=exercise)
    easy_completed = 0
    medium_completed = 0
    hard_completed = 0

    for conn in conns:
        if conn.completed_easy == True:
            easy_completed +=1
        if conn.completed_medium == True:
            medium_completed += 1
        if conn.completed_hard == True:
            hard_completed += 1
    return (easy_completed, medium_completed, hard_completed)




# sets the chapter-graph information
def create_chapter_graph(chapter):
    exercises = chapter.exercise_page_set.all()
    info = []
    counter=1
    for exercise in exercises:
        completed = 0
        connections = StudentConnectExercise.objects.filter(exercise=exercise)
        for conn in connections:
            if conn.completed_easy and conn.completed_medium and conn.completed_hard:
                completed += 1
        info.append([counter, completed])
        completed = 0
        counter += 1
    return info


# the subject-graph show how many percent all the students in a subject have completed
def create_subject_graph_values(subject):
    connections = StudentConnectSubject.objects.filter(subject=subject)
    subject_max_points = get_max_points(subject)

    # super_counter[0] -> how many students who have completed 0-9.99% percent of the subject
    # super_counter[2] -> how many students who have completed 20-29.99 percent of the subject and so on ...
    super_counter = [0 for x in range(10)]

    for connection in connections:
        if subject_max_points == 0:
            percent = 0
        else:
            percent = (connection.points / subject_max_points) * 100
        if percent <= 10:
            super_counter[0] +=1
        elif 10 < percent <= 20:
            super_counter[1] += 1
        elif 20 < percent <= 30:
            super_counter[2] += 1
        elif 30 < percent <= 40:
            super_counter[3] += 1
        elif 40 < percent <= 50:
            super_counter[4] += 1
        elif 50 < percent <= 60:
            super_counter[5] += 1
        elif 60 < percent <= 70:
            super_counter[6] += 1
        elif 70 < percent <= 80:
            super_counter[7] += 1
        elif 80 < percent <= 90:
            super_counter[8] += 1
        else:
            super_counter[9] += 1

    return super_counter

# see if a user is logged-in
def user_authenticated(user):
    if not user.is_authenticated():
        return False
    return True

stats/templates/stats/chapter_plot.html
{% extends 'stats/subject_chapters.html' %}
{% load static %}


{% block head_extend %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
 <!-- This script creates a plot with the use of data rendered for the view -->
    <script type="text/javascript">
      google.charts.load('current', {'packages':['line']});
      google.charts.setOnLoadCallback(drawChart);

        function drawChart() {

      var data = new google.visualization.DataTable();
      data.addColumn('number', 'Exercise Number');
      data.addColumn('number', 'Chapter-exercises');

      data.addRows(
        {{info}}
      );

      var options = {
        chart: {
          title: 'Students completed all tasks in an exercise',
        },
         width: 645,
         height: 400,
         backgroundColor: '#E5E4E2',
      };

      var chart = new google.charts.Line(document.getElementById('linechart_material'));

      chart.draw(data, options);
    }
    </script>
{% endblock %}

{% block graph %}
    <div class="col-md-9">

        <h4 class="text-center">{{chapter}}</h4>
       <div id="linechart_material" style="width:100%; height:70vh"></div>

    </div>
{% endblock %}

stats/templates/stats/exercise_bargraph.html
{% extends 'stats/subject_exercise.html' %}
{%load static %}

{% block head_extend %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <!-- This script creates a plot with the use of data rendered for the view -->

    <script type="text/javascript">
        google.charts.load("current", {packages:['corechart']});
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
        var data = google.visualization.arrayToDataTable([

            ["Element", "Students", { role: "style" } ],
            ["Easy", {{means.0}}, "#b87333"],
            ["Medium", {{means.1}}, "silver"],
            ["Hard", {{means.2}}, "gold"],

        ]);

        var view = new google.visualization.DataView(data);
        view.setColumns([0, 1,
                        { calc: "stringify",
                            sourceColumn: 1,
                            type: "string",
                            role: "annotation" },
                        2]);

        var options = {
            title: "Students who have completed Easy, Medium and Hard task",
            width: 600,
            height: 400,
            bar: {groupWidth: "70%"},

            legend: { position: "none" },
        };
        var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
        chart.draw(view, options);
    }
    </script>
{% endblock%}

{% block graph %}
    <div class="col-md-8">
        <h4 class="text-center">{{exercise.chapter}} -> {{ exercise.headline }}</h4>
        <div id="columnchart_values"></div>
    </div>
{% endblock %}

stats/templates/stats/statistics_index.html
{% extends 'adminpage/subject_overview.html' %}
{% load static %}
{% block subjects %}
    {% for subject in subjects %}
        <div class="collapse navbar-collapse" id="id_subject_overview_menu">
            <ul class="nav navbar-nav navbar-left" style="width:120px">
                <li style="float:left">
                    <a href="{% url 'stats:subject_overview' subject_pk=subject.pk %}" style="color:#337AB7;width:150px">
                        {{ subject }}
                    </a>

                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" id="id_nav_drop" style="width:-10px">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="id_menu_field" >
                        <span id="id_menu_dots" class="glyphicon glyphicon-option-vertical" style="color:#337AB7"></span>
                    </a>
                    <ul class="dropdown-menu" style="background-color:#383838">
                        <li ><a href="{% url 'adminpage:delete_subject' subject_pk=subject.pk %}" style="color:#337AB7">Delete</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    {% endfor %}
{% endblock %}


{% block extension%}

    <div class="col-md-10">
        <div class="text-center">
            <h2>Welcome to the Statistics Page</h2>
            <br>
            <h4>Here you can see different statistics for the various subjects</h4>
            <br>
            <h4>Check it out by clicking on one of the subjects in the sidebar</h4>
            <br>
        </div>

        <div class="modal-body row">
            <div class="col-md-6 text-center">
                <img src="{% static 'stats/img/pic1.png'%}" style="width:80%; height:30vh">
            </div>
            <div class="col-md-6 text-center">
                <img src="{% static 'stats/img/pic2.png'%}" style="width:80%; height:30vh">
            </div>
        </div>

    </div>

{% endblock %}

stats/templates/stats/statistics_subject.html
{% extends 'stats/statistics_index.html' %}



{% block extension%}
    <div class="col-md-10">
        <div class="text-center"><h3>Statistics for {{subject}} </h3></div><br>
        <div class="col-md-10 col-md-offset-1">
            <nav class="navbar navbar-inverse" style="text-align:center;">
                <div class="container-fluid">
                    <ul class="nav navbar-nav col-md-12">
                        <li class="col-md-2 col-md-offset-1"><a href="{% url 'stats:subject_overview' subject_pk=subject.pk %}">Overview</a></li>
                        <li class="col-md-2"><a href="{% url 'stats:subject_highscore' subject_pk=subject.pk %}">Highscore</a></li>
                        <li class="col-md-2"><a href="{% url 'stats:subject_pie_graph' subject_pk=subject.pk %}">Subject</a></li>
                        <li class="col-md-2"><a href="{% url 'stats:subject_chapters' subject_pk=subject.pk %}">Chapters</a></li>
                        <li class="col-md-2"><a href="{% url 'stats:subject_exercise' subject_pk=subject.pk %}">Exercises</a></li>
                    </ul>
                </div>
            </nav>
        {% block extra %}
        {% endblock%}
        </div>
    </div>



{% endblock %}

stats/templates/stats/subject_chapters.html
{% extends 'stats/statistics_subject.html' %}



{% block extra%}
<div class="row">
        <div class="col-md-2 sidebar" style="width:20%">
          <ul class="nav nav-sidebar navbar-inverse">
              <li class="active"><a href="#"><h4 style="color:grey">Chapters</h4><span class="sr-only">(current)</span></a></li>
              <!-- a way to get all the chapter in the chosen subject -->
                {% for chapter in subject.chapter_set.all %}
                    <li><a style="color:grey" href="{% url 'stats:chapter_plot' chapter_pk=chapter.pk subject_pk=subject.pk %}"> {{ chapter }}</a></li>
                {% endfor %}
          </ul>
        </div>
    {% block graph %}
        <div class="text-center">
            <h3> Choose a chapter</h3>
        </div>
    {% endblock %}
</div>

{% endblock %}

stats/templates/stats/subject_exercise.html
{% extends 'stats/statistics_subject.html' %}



{% block extra%}
<div class="row">
        <div class="col-md-2 sidebar" style="width:20%">
          <ul class="nav nav-sidebar navbar-inverse text-center">
              <li class="active"><a href="#"><h4 style="color:color:#3793c3">Chapters</h4><span class="sr-only">(current)</span></a></li>
              <!-- a way to get all the chapter in the chosen subject -->
              {% for chapter in subject.chapter_set.all %}
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a style="color:#3793c3" href="#" class="dropdown-toggle" data-toggle="dropdown">Chapter: {{chapter.chapter_number}}</a>
                            <ul class="dropdown-menu">
                                {% for exercise in chapter.exercise_page_set.all%}
                                    <li><a href="{% url 'stats:exercise_bargraph' subject_pk=subject.pk exercise_pk=exercise.pk %}"> {{exercise.headline}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>

                    </ul>

                </div>
              {% endfor %}
          </ul>
        </div>
</div>
{% endblock %}

{% block graph %}
<div class="text-center">
    <h4>Choose an exercise from a chapter</h4>
</div>
{% endblock %}

stats/templates/stats/subject_graph.html
{% extends 'stats/statistics_subject.html' %}


<!--  doing this to make a pie-chart -->
{% block head_extend %}
 <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
     <!-- This script creates a plot with the use of data rendered for the view -->
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart(a) {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ['0-10 %', {{ values.0 }}],
          ['11-20 %', {{ values.1 }}],
          ['21-30 %', {{ values.2 }}],
          ['31-40 %', {{ values.3 }}],
          ['41-50 %', {{ values.4 }}],
          ['51-60 %', {{ values.5 }}],
          ['61-70 %', {{ values.6 }}],
          ['71-80 %', {{ values.7 }}],
          ['81-90 %', {{ values.8 }}],
          ['91-100 %', {{ values.9 }}]
        ]);

        // Set chart options
        var options = {'title':'Students Course Completed',
                        };


        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>

{% endblock %}

{% block extra%}
    <div id="chart_div" style="width:100%; height:50vh;"></div>
{% endblock %}

stats/templates/stats/subject_highscore.html
{% extends 'stats/statistics_subject.html' %}



{% block extra%}
    <div class="col-sm-12">
        <div class="col-md-8 col-md-offset-2 text-center">
            <table class="table table-bordered" style="border-color: #303030;">
              <thead>
                <tr style="background-color:green; color:white">
                  <th class="text-center" style="border-color: #303030;">Rank</th>
                  <th class="text-center" style="border-color: #303030;">Username</th>
                  <th class="text-center" style="border-color: #303030;">Score</th>
                  <th class="text-center" style="border-color: #303030;">Percent</th>

                </tr>
              </thead>
              <tbody>
                {% for info in highscore_info %}
                    <tr style="background-color:green; color:white">
                        <th class="text-center" style="border-color: #303030;">{{info.0}}</th>
                        <td class="text-center" style="border-color: #303030;">{{info.1.user}}</td>
                        <td class="text-center" style="border-color: #303030;">{{info.1.points}}</td>
                        <td class="text-center" style="border-color: #303030;">{{info.2}}</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
    </div>

{% endblock %}

stats/templates/stats/subject_overview.html
{% extends 'stats/statistics_subject.html' %}



{% block extra%}
    <div class="col-sm-12">
        <div class="col-md-8 col-md-offset-2 text-center" style="background-color:#ffb914">
            <h3> <u>{{subject}}</u></h3>
            <p>Subject name: {{subject.subject_name}}</p>
            <p>Professor: {{subject.get_full_name}}</p>
            <p>Contact: {{subject.professor_email}}</p>
            <hr>
            <h5>Number of students: {{num_students}}</h5>
        </div>
    </div>

{% endblock %}