adminpage/urls.py
from django.conf.urls import url
from . import views

app_name='adminpage'

urlpatterns = [
    url(r'^$', views.admin_index, name='admin_index'),
    url(r'^tilbakemeldinger/$',views.tilbakemeldinger, name="tilbakemeldinger"),
    url(r'^tilbakemeldinger/(?P<subject_pk>[A-Za-z0-9]+)/$', views.chapters, name="chapters"),
    url(r'^tilbakemeldinger/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.chapter_feedback, name="chapter_feedback"),

    url(r'^subjects/$', views.subject_overview, name='subject_overview'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/$', views.chapter_overview, name='chapter_overview'),
    url(r'^subjects/new_subject/$', views.new_subject, name='new_subject'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/change_chapter/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.change_chapter, name='change_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/new_chapter/$', views.new_chapter, name='new_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/delete/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.delete_chapter, name='delete_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/delete/$', views.delete_subject, name='delete_subject'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.exercise_overview,name='exercise_overview'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/new_exercise/$', views.new_exercise,
        name='new_exercise'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/(?P<exercise_pk>[A-Za-z0-9]+)/delete/$', views.delete_exercise,
        name='delete_exercise'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/change_exercise/(?P<exercise_pk>[A-Za-z0-9]+)/$', views.change_exercise,
        name='change_exercise'),

]

main/urls.py
from django.conf.urls import url
from . import views

app_name='main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^userregister/$', views.userregister, name='userregister'),
    url(r'^professorregister/$', views.professorregister, name='professorregister'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_subject/(?P<subject_pk>[A-Za-z0-9]+)$', views.add_subject, name='add_subject'),

]

nysil/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
    url(r'^my_subjects/', include('my_subjects.urls')),
    url(r'^adminpage/', include('adminpage.urls')),
    url(r'^progress/', include('progress.urls')),
    url(r'^adminpage/statistics/', include('stats.urls')),

]

stats/urls.py
from django.conf.urls import url
from . import views

app_name='stats'

urlpatterns = [
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/graph/(?P<exercise_pk>[A-Za-z0-9]+)/$', views.exercise_bargraph, name='exercise_bargraph'),
    url(r'^$', views.statistics_index, name='statistics_index'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/$', views.statistics_subject, name='statistics_subject'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/overview/$', views.subject_overview, name='subject_overview'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/highscore/$', views.subject_highscore, name='subject_highscore'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/chapters/$', views.subject_chapters, name='subject_chapters'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/exercises/$', views.subject_exercise, name='subject_exercise'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/chapter_plot/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.chapter_plot, name='chapter_plot'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/graph/$', views.subject_pie_graph, name='subject_pie_graph'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver





class Subject(models.Model):
    subject_code = models.CharField(max_length=20, primary_key=True) # primary key
    subject_name = models.CharField(max_length=30)
    professor_firstname = models.CharField(max_length=30)
    professor_lastname = models.CharField(max_length=30)
    professor_email = models.EmailField()

    class Meta:
        ordering = ['subject_code']

    # nice when printing a Subject-object
    def __str__(self):
        return self.subject_code

    def get_full_name(self):
        return self.professor_firstname + " " + self.professor_lastname

    get_full_name.short_description = 'Professor' # headline of professor-column in the admin-table



class Chapter(models.Model):

    # order the chapter-list by chapter_number
    class Meta:
        unique_together = ('subject', 'chapter_number') # handle the exception this may cause
        ordering = ['chapter_number']

    chapter_number = models.PositiveIntegerField(default = 0)
    chapter_name = models.CharField(max_length=50)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE) # to controll which subject the theme belongs to


    # nice when printing a Chapter-object
    def __str__(self):
        return "Chapter " + str(self.chapter_number) + ": " + str(self.chapter_name)

    def get_number_and_name(self):
        return "Chapter" + str(self.chapter_number) + ": " + str(self.chapter_name)
    get_number_and_name.short_description = 'Chapter'



class Exercise_Page(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)  # to controll which chapter the exercise_page belongs to

    youtube_id = models.CharField(max_length=40)
    headline = models.CharField(max_length=30)

    # explanation describes what topics the exercises covers, so its easy to se for the students
    explanation = models.TextField(max_length=150)


    # attributes for the easy question
    easy_question = models.TextField(default='')
    easy_answer = models.CharField(max_length=30,default='')
    easy_points = models.PositiveIntegerField(default=0)

    # attributes for the medium question
    medium_question = models.TextField(default='')
    medium_answer = models.CharField(max_length=30,default='')
    medium_points = models.PositiveIntegerField(default=0)

    # attributes for the hard question
    hard_question = models.TextField(default='')
    hard_answer = models.CharField(max_length=30,default='')
    hard_points = models.PositiveIntegerField(default=0)



# a connecton between a user and a subject which controlls the points the student have in the subject
class StudentConnectSubject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)




# every time a student follows a subject, there is a relation between the student and all the exercises in the subject
class StudentConnectExercise(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise_Page, on_delete=models.CASCADE)

    # theese variables controls if the student has answered correct on the questions in the exercise, so the student
    # cant answer correct all the time on the same question and gain infinity points
    completed_easy = models.BooleanField(default=False)
    completed_medium = models.BooleanField(default=False)
    completed_hard = models.BooleanField(default = False)

# ----------------------------------------------------------

# UserProfile is a model with a OneToOneField to User. This let us add fields to the nysil-user, which is importamt
# because users need to have foreign-keys to their subjects

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    #test = models.IntegerField(default=5)
    subjects = models.ManyToManyField(Subject, blank=True)


    def add_subject(self, subject_pk):
        subject = Subject.objects.get(pk=subject_pk)
        student_subject_conn = StudentConnectSubject(user=self.user, subject=subject)
        find_student_subject_conn = StudentConnectSubject.objects.filter(user=self.user,subject=subject).exists()
        if not find_student_subject_conn:
            student_subject_conn.save()

        # create a StudentConnectExercise between the current student and all the exercises in the subject
        for chapter in subject.chapter_set.all():
            for exercise in chapter.exercise_page_set.all():
                connection = StudentConnectExercise(user=self.user, exercise=exercise)
                # checking for a connection between user and exercise that already exists
                find_connection = StudentConnectExercise.objects.filter(user=self.user,exercise=exercise).exists()
                if not find_connection:
                    connection.save()
        already_follows = self.subjects.filter(pk=subject_pk).exists()
        if not already_follows:

            self.subjects.add(Subject.objects.get(pk=subject_pk))


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

# ----------------------------------------------------------


class Comment(models.Model):
    publisher = models.ForeignKey(User)
    published_time = models.DateTimeField(auto_now_add=True, blank=True)
    text = models.TextField()
    chapter = models.ForeignKey(Chapter)
    exercise = models.ForeignKey(Exercise_Page)


    def get_published_time(self):
        return str(self.published_time)[:16]

adminpage/forms.py
from django import forms
from main.models import Subject, Chapter, Exercise_Page

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['subject_code','subject_name','professor_firstname','professor_lastname','professor_email']


class ChapterForm(forms.ModelForm):

    class Meta:
        model = Chapter
        fields = ['chapter_number','chapter_name']


class ExerciseForm(forms.ModelForm):

    class Meta:
        model = Exercise_Page
        exclude = ['chapter']

adminpage/templates/adminpage/admin_header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>NYSIL</title>
	<meta charset="utf-8">

    {% load static %}
    <link rel="stylesheet" href="{% static 'adminpage/css/customize.css' %}" type="text/css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'adminpage/img/n_favicon.png' %}" type="image/x-icon" />

	<!-- Latest compiled and minified CSS --><!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
	integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
	crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
	integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
	crossorigin="anonymous">

	 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
	integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
	crossorigin="anonymous"></script>

	<meta name="viewport" content = "width=device-width, initial-scale=1.0">


    <link rel="stylesheet" href="{% static 'main/css/header.css'%}" type = "text/css"/>
    <!-- Use this block to extend the header-->
    {% block head_extend %}
    {% endblock %}
</head>
<!-- Layout to the background -->
<body class="body" style="background-color: #E5E4E2;">

<div id="wrapper">

        <!-- Navbar on the top -->
        <br>
        <br>
        <br>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">

                <!--mobile friendly, changes the navbar to a dropdown buttion when the screen gets to small
                 + button to the left which taces you to the index-page -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
				    </button>
                    <a href="{% url 'main:index' %}" class="navbar-brand"><img src="{% static 'main/img/ny_logo.png'%}" style="width:100px;height:27px;margin-top:-4px;margin-left:-3px"></a>
                </div>

                <!-- Navbar items, collaborates with collapse by id (data-target) -->
                <div class="collapse navbar-collapse" id="mainNavBar">
                    <ul class="nav navbar-nav">

                        <!-- Dropdown menu for my subjects in the navbar -->
                        <li><a href="{% url 'adminpage:subject_overview' %}">Subjects</a></li>
                        <li><a href="{% url 'adminpage:tilbakemeldinger' %}">Feedback</a></li>
                        <li><a href="{% url 'stats:statistics_index'%}">Statistics</a></li>

                    </ul>

                    <!-- Button for login -->
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-right:-10px">
                                    Contact
                                    <span class="caret" style="width:2px;height:2px"></span></a>
                                <ul class="dropdown-menu">
                                    <!-- adds all the subjects to "My Subjects"-dropown -->
                                    <li><h5 href="" style="margin-left:5px">Vebjørn Fjeldberg: vebjorpf@stud.ntnu.no</h5></li>
                                    <li><h5 href="" style="margin-left:5px">Oscar Kierulf: oscark@stud.ntnu.no</h5></li>
                                    <li><h5 href="" style="margin-left:5px">Espen Lindstad: espenoli@stud.ntnu.no</h5></li>
                                    <li><h5 href="" style="margin-left:5px">Kristoffer Saastad: kristogs@stud.ntnu.no</h5></li>
                                </ul>
                            </li>
				        </li>
                        <li class="dropdown">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-right: 15px">Welcome, Prof. {{user}}
                                    <span class="glyphicon glyphicon-option-vertical" style="width:2px;height:2px"></span></a>
                                <ul class="dropdown-menu">
                                    <!-- adds all the subjects to "My Subjects"-dropown -->
                                    <li><a href="{% url 'main:logout_user' %}">Logout</a></li>
                                </ul>
                            </li>
				        </li>
                    </ul>


                </div>
            </div>
        </nav>
    </div>

    <!-- Block extend-files will use: -->
    {% block content %}
        <div class="container-fluid" style="text-align: center;">
            <div class="row">

                <h2>Welcome to the Adminpage</h2>
                <br>
                <div>As a NYSIL-professor, you have the possibility to create subjects. When you have created <br>
                the subject, you can add the subject's chapters. Under each chapter, there can be several videos <br>
                with following tasks. <br><br>
                When students finishes the videos and the tasks, you can reed their feedback and look at the <br>
                statistics to possibly improve your content. <br>
            </div>
        </div>



            </div>

                <div class="row" style="text-align: center; margin-top: 30px">
                    <button onclick="window.location.href='subjects';" style="padding: 50px 84px 50px 84px; background: #0080FF; border-radius: 4px; font-size: 18px; color: white" type="submit" class="btn btn">Subjects</button>

                    <button onclick="window.location.href='tilbakemeldinger';" style="padding: 50px 84px 50px 84px; background: #0080FF; border-radius: 4px; font-size: 18px; color: white" type="submit" class="btn btn">Feedback</button>

                    <button onclick="window.location.href='statistics';" style="padding: 50px 84px 50px 84px; background: #0080FF; border-radius: 4px; font-size: 18px; color: white" type="submit" class="btn btn">Statistics</button>
                </div>
            </div>
    {% endblock%}


</div>


</body>

adminpage/templates/adminpage/chapter_feedback.html
{% extends 'adminpage/tilbakemeldinger.html' %}

{% block extension %}
<div class ="col-md-10">

        <h5>Feedback for {{ subject }} <span class="glyphicon glyphicon-arrow-right"></span> {{ chapter }}</h5>
        <table class="table table-striped">
        <thead>
            <tr style="background-color:#303030; color:white">
                <th>Date</th>
                <th>User</th>
                <th>Exersice</th>
                <th>Comment</th>
            </tr>
        </thead>

        <tbody>
        {% for comment in chapter.comment_set.all %}
            <tr>
                <th class="col-md-2"> {{ comment.get_published_time }}</th>
                <th class="col-md-1"> {{ comment.publisher }}</th>
                <td class="col-md-2"> {{ comment.exercise.headline }}</td>
                <td> {{ comment.text }}</td>

            </tr>


        {% endfor %}

        </tbody>


    </table>


</div>
{% endblock %}

adminpage/templates/adminpage/chapter_overview.html
{% extends 'adminpage/subject_overview.html' %}

{% block extension %}

<div class="col-md-10">
    <div style ="width:90%">
        <div style="float: left; width: 50%">
            <h3> Chapter overview for {{ subject }} </h3>
        </div>

        <div style="float: right; width: 0%">
            <!-- wrapped the "add_chapter"-button inside a block because we want to give the button some new
             functionality after it has been clicked -->
            {% block chapter %}
                <!-- Button that will send you to add_chapter-template -->
                <div id="add_chapter">
                    <a class="btn btn-large btn-success" href="{% url 'adminpage:new_chapter' subject_pk=subject.pk %}">New chapter</a>
                </div>
            {% endblock %}
        </div>

    </div>

    <table class="table table-striped">
        <!-- headlines to the columns in the table -->

        <thead>
            <tr>
                <th>Chapter</th>
                <th>Name</th>
                <th>Contents</th>
                <th>CHANGE</th>
                <th>DELETE</th>
            </tr>
        </thead>

        <!-- all the table-content -->
        <tbody>
            {% for chapter in subject.chapter_set.all %}
                <tr>
                    <th scope="row">{{ chapter.chapter_number }}</th>
                    <th scope="row">{{ chapter.chapter_name }}</th>
                    <td><div><a class="btn btn-xs btn-warning" href="{% url 'adminpage:exercise_overview' chapter_pk=chapter.pk subject_pk=subject.pk %}">Content</a></div></td>

                    <td><div><a class="btn btn-xs btn-info" href="{% url 'adminpage:change_chapter' subject_pk=subject.pk chapter_pk=chapter.pk %}">CHANGE</a></div></td>
                    <!-- this button shall delete the chapter and take us back to the same url -->
                    <td><div><a class="btn btn-xs btn-danger" href="{% url 'adminpage:delete_chapter' subject_pk=subject.pk chapter_pk=chapter.pk %}">DELETE</a></div></td>
                </tr>
            {% endfor%}

        </tbody>

    </table>

</div>
{% endblock%}

adminpage/templates/adminpage/chapters.html
{% extends 'adminpage/tilbakemeldinger.html' %}

{% block extension %}

<div class="col-md-10">
    <div style ="width:90%">
        <div style="float: left; width: 50%">
            <h3> Chapter overview for {{ subject }} </h3>
        </div>



    </div>
    <table class="table table-striped">
        <!-- headlines to the columns in the table -->
        <thead>
            <tr>
                <th>Chapter</th>
                <th>Name</th>
                <th>Feedback</th>
            </tr>
        </thead>

        <!-- all the table-content -->
        <tbody>
            {% for chapter in subject.chapter_set.all %}
                <tr>
                    <th scope="row">{{ chapter.chapter_number }}</th>
                    <td> {{ chapter.chapter_name }}</td>
                    <td><div><a class="btn btn-xs btn-danger" href="{% url 'adminpage:chapter_feedback' subject_pk=subject.pk chapter_pk=chapter.pk %}">See Feedback</a></div></td>
                </tr>
            {% endfor%}

        </tbody>

    </table>

</div>
{% endblock%}

adminpage/templates/adminpage/exercise_overview.html
{% extends 'adminpage/subject_overview.html' %}

{% block extension %}
<div class ="col-md-10">
    <div class="col-md-12">
    <div style ="width:90%">
        <div style="float: left; width: 60%">
            <h4>{{ subject }} <span class="glyphicon glyphicon-arrow-right"></span> {{ chapter }} <span class="glyphicon glyphicon-arrow-right"></span> Exercises </h4>
            <br>
        </div>

        <div style="float: right; width: 0%">
            <!-- wrapped the "add_chapter"-button inside a block because we want to give the button some new
             functionality after it has been clicked -->
            {% block add_button %}
                <!-- Button that will send you to new_exercise-template -->
                <div id="add_exercise">
                    <a class="btn btn-large btn-success" href=" {% url 'adminpage:new_exercise' subject_pk=subject.pk chapter_pk=chapter.pk %}">New exercise</a>
                </div>
            {% endblock %}
        </div>

    </div>




    <div style="width:100%">
    <table class="table table-striped">
        <thead>
            <tr style="background-color:#303030; color:white">
                <th>Title</th>
                <th>Explanation</th>
                <th>CHANGE</th>
                <th>DELETE</th>
            </tr>
        </thead>

        <tbody>
        {% for exercise in chapter.exercise_page_set.all %}
            <tr>
                <th> {{ exercise.headline }}</th>
                <td> {{ exercise.explanation }}</td>
                <td><div><a class="btn btn-xs btn-info" href="{% url 'adminpage:change_exercise' subject_pk=subject.pk chapter_pk=chapter.pk exercise_pk=exercise.pk %}">CHANGE</a></div></td>
                <td><div><a class="btn btn-xs btn-danger" href=" {% url 'adminpage:delete_exercise' subject_pk=subject.pk chapter_pk=chapter.pk exercise_pk=exercise.pk %} ">DELETE</a></div></td>



            </tr>


        {% endfor %}

        </tbody>


    </table>
    </div>
</div>
</div>
{% endblock %}

adminpage/templates/adminpage/subject_overview.html
{% extends 'adminpage/admin_header.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar navbar-inverse">
              <!-- This li takes us back to the subject_overvieq -->
              <li ><p id="id_fagoversikt"><h3 id="id_fagoversikt_text" style="color:#337AB7;margin-left:10px">Overview</h3><span class="sr-only">(current)</span></p></li>
              <p class="center-large" style="margin-left:20px"><a href="{% url 'adminpage:new_subject' %}"><span class="glyphicon glyphicon-plus"></span>  Add subject</a></p>
              <!-- a way to get all the chapter in the chosen subject -->
              {% block subjects %}
                {% for subject in subjects %}
                <div class="collapse navbar-collapse" id="id_subject_overview_menu">
                    <ul class="nav navbar-nav navbar-left" style="width:120px">
                      <li style="float:left">
                          <a href="{% url 'adminpage:chapter_overview' subject_pk=subject.pk %}" style="color:#337AB7;width:150px">
                              {{ subject }}
                          </a>

                      </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right" id="id_nav_drop" style="width:-10px">
                        <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="id_menu_field" >
                                <span id="id_menu_dots" class="glyphicon glyphicon-option-vertical" style="color:#337AB7"></span>
                           </a>
                            <ul class="dropdown-menu" style="background-color:#383838">
                                <li ><a href="{% url 'adminpage:delete_subject' subject_pk=subject.pk %}" style="color:#337AB7">Delete</a></li>
                            </ul>
                        </li>
                    </ul>
                 </div>
                {% endfor %}
              {% endblock %}

          </ul>
        </div>

    {% block extension %}

        <div class="container-fluid" style="text-align: center;">
            <div style="font-size: 30px">
                Welcome to the Subjects Page
            </div>
            <br>
            <div>
                Here you can create a subject or enter a existing one to create a new chapter or a task
                <br>
                <br>
                Check it out by clicking on one of the subjects in the sidebar
            </div>
            <br>
            <div class="col-md-4" style="margin-left: 50px">
                <img src="{% static 'adminpage/img/oversikt.png'%}" style="width: 380px; height: 200px">
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-4">
                <img src="{% static 'adminpage/img/oppgave.png'%}" style="width: 380px; height: 200px">
            </div>
        </div>
{% endblock %}




</div>
</div>
{% endblock%}

adminpage/templates/adminpage/tilbakemeldinger.html
{% extends 'adminpage/admin_header.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar navbar-inverse">
              <!-- This li takes us back to the subject_overvieq -->
              <li ><p id="id_fagoversikt"><h3 id="id_fagoversikt_text" style="color:#337AB7;margin-left:10px">Overview</h3><span class="sr-only">(current)</span></p></li>
              <p class="center-large" style="margin-left:20px"><a href="{% url 'adminpage:new_subject' %}"><span class="glyphicon glyphicon-plus"></span>  Add subject</a></p>
              <!-- a way to get all the chapter in the chosen subject -->
                {% for subject in subjects %}
                <div class="collapse navbar-collapse" id="id_subject_overview_menu">
                    <ul class="nav navbar-nav navbar-left" style="width:120px">
                      <li style="float:left">
                          <a href="{% url 'adminpage:chapters' subject_pk=subject.pk %}" style="color:#337AB7;width:150px">
                              {{ subject }}
                          </a>
                      </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right" id="id_nav_drop" style="width:-10px">
                        <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="id_menu_field" >
                                <span id="id_menu_dots" class="glyphicon glyphicon-option-vertical" style="color:#337AB7"></span>
                           </a>
                            <ul class="dropdown-menu" style="background-color:#383838">
                                <li ><a href="{% url 'adminpage:delete_subject' subject_pk=subject.pk %}" style="color:#337AB7">Delete</a></li>
                            </ul>
                        </li>
                    </ul>
                 </div>
                {% endfor %}

          </ul>
        </div>

    {% block extension %}
    <div class="container-fluid" style="text-align: center;">
      <div style="font-size: 30px">
        Welcome to the Feedback Page
      </div>
      <br>
      <div>
        Here you can see your students' feedback related to a video or it's given tasks
        <br>
        <br>
        Check it out by clicking on one of the subjects in the sidebar
      </div>
      <br>
    <div class="col-md-4" style="margin-left: 50px">
      <img src="{% static 'adminpage/img/feedback.png'%}" style="width: 380px; height: 200px">
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-4">
      <img src="{% static 'adminpage/img/graph.png'%}" style="width: 380px; height: 200px">
    </div>
    </div>
    {% endblock %}
    </div>



</div>
{% endblock%}