main/urls.py
from django.conf.urls import url
from . import views

app_name='main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^userregister/$', views.userregister, name='userregister'),
    url(r'^professorregister/$', views.professorregister, name='professorregister'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_subject/(?P<subject_pk>[A-Za-z0-9]+)$', views.add_subject, name='add_subject'),

]

my_subjects/urls.py
from django.conf.urls import url
from . import views

from main.models import Subject

app_name='my_subjects'

# subject_pk: the primary key for the subject ex "TDT4140"
# chapter_pk: the primary key for the theme ex "1"
# exercise_pk: the primary key for the exercise_page

urlpatterns = [
    # example .../my_subjects/TDT4140
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/$', views.subject_view, name='subject_view'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.all_exercises_view, name='all_exercises_view'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/(?P<exercise_pk>[A-Za-z0-9]+)/$', views.exercise_view,
        name='exercise_view'),
]

nysil/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
    url(r'^my_subjects/', include('my_subjects.urls')),
    url(r'^adminpage/', include('adminpage.urls')),
    url(r'^progress/', include('progress.urls')),
    url(r'^adminpage/statistics/', include('stats.urls')),

]

progress/urls.py
from django.conf.urls import url
from . import views

app_name='progress'

urlpatterns = [
    url(r'^$', views.my_progress, name='my_progress'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/highscore/$', views.highscore, name='highscore'),

]

progress/models.py
from django.db import models

# Create your models here.

progress/views.py
from django.shortcuts import render
from main.models import StudentConnectSubject, Subject


def my_progress(request):
    user = request.user
    context = {}
    # subjects the user follows
    user_subjects = StudentConnectSubject.objects.filter(user=user)

    # the progress_overview is splitted into three columns, and we want to divide the user_subjects in theese columns
    # form of the columns = [[student_subject_connection, user_rank_in_subject, tasks_completed_percent][]..........]
    context['first_column'],  context['second_column'], context['third_column'] = set_view_context(user_subjects, user)
    return render(request, 'progress/progress_overview.html', context)


def highscore(request, subject_pk):
    user = request.user
    subject = Subject.objects.get(pk=subject_pk)
    info = set_highscore_info(subject)
    context = {'info': info, 'subject': subject}
    return render(request, 'progress/highscore.html', context)


# ------------------- Help-Methods ---------------------------

# sets the info in the subject highscore
def set_highscore_info(subject):
    subject_connections = StudentConnectSubject.objects.filter(subject=subject).order_by('-points')
    info = []
    counter = 1

    for conn in subject_connections:
        info.append([counter,conn])
        counter += 1

    return info

# sets the view_context that my_progress shall render
def set_view_context(subjects, user):
    first_subjects, second_subjects, third_subjects = split_subjects(subjects)
    first_column = []
    second_column = []
    third_column = []

    for subject in first_subjects:
        first_column.append(merge_info(subject,user))

    for subject in second_subjects:
        second_column.append(merge_info(subject, user))

    for subject in third_subjects:
        third_column.append(merge_info(subject, user))

    return first_column,second_column,third_column



def merge_info(subject_conn, user):
    user_subject_conn = StudentConnectSubject.objects.get(user=user, subject=subject_conn.subject)
    info = []

    # this adds the connection between user and subject, so we can easy get the user-score in the subject
    info.append(subject_conn)

    # adds the user-rank in the subject on the form "1 of 100"
    info.append(find_rank(subject_conn.subject, user))

    # adds how many percent of the tasks the user has completed in the subject
    divider = get_max_points(subject_conn.subject)
    info.append(str(round((user_subject_conn.points*100)/divider,1)) + "%" if divider>0 else "0 %")
    return info




# this method splits the subjects in to three lists
def split_subjects(subjects):
    first_column = []
    second_column = []
    last_column = []
    counter = 0
    for subject in subjects:
        if counter % 3 == 0:
            first_column.append(subject)
        elif counter % 3 == 1:
            second_column.append(subject)
        else:
            last_column.append(subject)
        counter += 1
    return first_column, second_column, last_column


# this is a help-method that finds the user rank in a spesific subject
def find_rank(subject,user):
    students_in_subject = StudentConnectSubject.objects.filter(subject=subject)
    students_in_subject = students_in_subject.order_by('-points')
    rank = 1
    for student in students_in_subject:
        if student.user == user:
            return str(rank) + " of " + str(students_in_subject.count())
        rank += 1


# this is a help-method for finding the maxium possible points a user can get in a subject
def get_max_points(subject):
    chapters = subject.chapter_set.all()
    points = 0
    for chapter in chapters:
        exercises = chapter.exercise_page_set.all()
        for exercise in exercises:
            points += exercise.easy_points + exercise.medium_points + exercise.hard_points
    return points

progress/templates/progress/highscore.html
{% extends 'main/header.html' %}

<!-- HTML for making a topscore-table -->
{% block content %}
    <div style="float:left; width:20%">
        <a class="btn btn-md" href="{% url 'progress:my_progress' %}" style="color:white; background:#3793C3"><span class="glyphicon glyphicon-chevron-left"></span> Back to progress</a>
    </div>
    <div class="col-md-8 col-md-offset-2 text-center">
        <h1>Highscore List for {{subject}}</h1>
        <br>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="text-center">Rank</th>
                    <th class="text-center">Username</th>
                    <th class="text-center">points</th>
                </tr>
            </thead>
            <tbody>
                {% for info in info %}
                <tr>
                    <th scope="row" class="text-center">{{info.0}}</th>
                    <td>{{info.1.user}}</td>
                    <td>{{info.1.points}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

progress/templates/progress/progress_overview.html
{% extends 'main/header.html' %}


{% block content %}
<div class="modal-body row">
  <div class="col-md-4">
    {% for info in first_column %}
      <div style="width:100%; background-color:#303030; color:white; display:inline-block;">
          <div class="text-center">

              <h3>{{info.0.subject }}</h3>
              <a href="{% url 'my_subjects:subject_view' subject_pk=info.0.subject.pk%}">Go to subject</a>
              <hr>
              <h4><u>Subject Information</u></h4>
              <h6>Subject Name: {{info.0.subject.subject_name}}</h6>
              <h6>Contact: {{info.0.subject.professor_email }}</h6>
              <hr>
              <h4><u>Personal Information</u></h4>
              <h6>Points: {{info.0.points}}</h6>
              <h6>Rank: {{info.1}}</h6>
              <h6>Tasks completed: {{info.2}} </h6>
              <hr>
              <h5><a href="{% url 'progress:highscore' subject_pk=info.0.subject.pk%}"> See highscore list</a></h5>
          </div>
      </div>
      <br><br>
    {% endfor %}
  </div>
  <div class="col-md-4">
    {% for info in second_column %}
      <div style="width:100%; background-color:#5e5e5e; color:white; display:inline-block;">
          <div class="text-center">

              <h3>{{info.0.subject }}</h3>
              <a href="{% url 'my_subjects:subject_view' subject_pk=info.0.subject.pk%}">Go to subject</a>

              <hr>
              <h4><u>Subject Information</u></h4>
              <h6>Subject Name: {{info.0.subject.subject_name}}</h6>
              <h6>Contact: {{info.0.subject.professor_email }}</h6>
              <hr>
              <h4><u>Personal Information</u></h4>
              <h6>Points: {{info.0.points}}</h6>
              <h6>Rank: {{info.1}}</h6>
              <h6>Tasks completed: {{info.2}} </h6>
              <hr>
              <h5><a href="{% url 'progress:highscore' subject_pk=info.0.subject.pk%}"> See highscore list</a></h5>
          </div>
      </div>
      <br><br>
    {% endfor %}
  </div>
  <div class="col-md-4">
    {% for info in third_column %}

      <div style="width:100%; background-color:#303030; color:white; display:inline-block">
          <div class="text-center">

              <h3>{{info.0.subject }}</h3>
              <a href="{% url 'my_subjects:subject_view' subject_pk=info.0.subject.pk%}">Go to subject</a>

              <hr>
              <h4><u>Subject Information</u></h4>
              <h6>Subject Name: {{info.0.subject.subject_name}}</h6>
              <h6>Contact: {{info.0.subject.professor_email }}</h6>
              <hr>
              <h4><u>Personal Information</u></h4>
              <h6>Points: {{info.0.points}}</h6>
              <h6>Rank: {{info.1}}</h6>
              <h6>Tasks completed: {{info.2}} </h6>
              <hr>
              <h5><a href="{% url 'progress:highscore' subject_pk=info.0.subject.pk%}">See highscore list</a></h5>
          </div>
      </div>
      <br><br>
    {% endfor %}
</div>
{% endblock %}