adminpage/urls.py
from django.conf.urls import url
from . import views

app_name='adminpage'

urlpatterns = [
    url(r'^$', views.admin_index, name='admin_index'),
    url(r'^tilbakemeldinger/$',views.tilbakemeldinger, name="tilbakemeldinger"),
    url(r'^tilbakemeldinger/(?P<subject_pk>[A-Za-z0-9]+)/$', views.chapters, name="chapters"),
    url(r'^tilbakemeldinger/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.chapter_feedback, name="chapter_feedback"),

    url(r'^subjects/$', views.subject_overview, name='subject_overview'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/$', views.chapter_overview, name='chapter_overview'),
    url(r'^subjects/new_subject/$', views.new_subject, name='new_subject'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/change_chapter/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.change_chapter, name='change_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/new_chapter/$', views.new_chapter, name='new_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/delete/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.delete_chapter, name='delete_chapter'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/delete/$', views.delete_subject, name='delete_subject'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.exercise_overview,name='exercise_overview'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/new_exercise/$', views.new_exercise,
        name='new_exercise'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/(?P<exercise_pk>[A-Za-z0-9]+)/delete/$', views.delete_exercise,
        name='delete_exercise'),
    url(r'^subjects/(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/change_exercise/(?P<exercise_pk>[A-Za-z0-9]+)/$', views.change_exercise,
        name='change_exercise'),

]

main/urls.py
from django.conf.urls import url
from . import views

app_name='main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^userregister/$', views.userregister, name='userregister'),
    url(r'^professorregister/$', views.professorregister, name='professorregister'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^search/$', views.search, name='search'),
    url(r'^add_subject/(?P<subject_pk>[A-Za-z0-9]+)$', views.add_subject, name='add_subject'),

]

my_subjects/urls.py
from django.conf.urls import url
from . import views

from main.models import Subject

app_name='my_subjects'

# subject_pk: the primary key for the subject ex "TDT4140"
# chapter_pk: the primary key for the theme ex "1"
# exercise_pk: the primary key for the exercise_page

urlpatterns = [
    # example .../my_subjects/TDT4140
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/$', views.subject_view, name='subject_view'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/$', views.all_exercises_view, name='all_exercises_view'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/(?P<chapter_pk>[A-Za-z0-9]+)/(?P<exercise_pk>[A-Za-z0-9]+)/$', views.exercise_view,
        name='exercise_view'),
]

nysil/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls')),
    url(r'^my_subjects/', include('my_subjects.urls')),
    url(r'^adminpage/', include('adminpage.urls')),
    url(r'^progress/', include('progress.urls')),
    url(r'^adminpage/statistics/', include('stats.urls')),

]

progress/urls.py
from django.conf.urls import url
from . import views

app_name='progress'

urlpatterns = [
    url(r'^$', views.my_progress, name='my_progress'),
    url(r'^(?P<subject_pk>[A-Za-z0-9]+)/highscore/$', views.highscore, name='highscore'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver





class Subject(models.Model):
    subject_code = models.CharField(max_length=20, primary_key=True) # primary key
    subject_name = models.CharField(max_length=30)
    professor_firstname = models.CharField(max_length=30)
    professor_lastname = models.CharField(max_length=30)
    professor_email = models.EmailField()

    class Meta:
        ordering = ['subject_code']

    # nice when printing a Subject-object
    def __str__(self):
        return self.subject_code

    def get_full_name(self):
        return self.professor_firstname + " " + self.professor_lastname

    get_full_name.short_description = 'Professor' # headline of professor-column in the admin-table



class Chapter(models.Model):

    # order the chapter-list by chapter_number
    class Meta:
        unique_together = ('subject', 'chapter_number') # handle the exception this may cause
        ordering = ['chapter_number']

    chapter_number = models.PositiveIntegerField(default = 0)
    chapter_name = models.CharField(max_length=50)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE) # to controll which subject the theme belongs to


    # nice when printing a Chapter-object
    def __str__(self):
        return "Chapter " + str(self.chapter_number) + ": " + str(self.chapter_name)

    def get_number_and_name(self):
        return "Chapter" + str(self.chapter_number) + ": " + str(self.chapter_name)
    get_number_and_name.short_description = 'Chapter'



class Exercise_Page(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)  # to controll which chapter the exercise_page belongs to

    youtube_id = models.CharField(max_length=40)
    headline = models.CharField(max_length=30)

    # explanation describes what topics the exercises covers, so its easy to se for the students
    explanation = models.TextField(max_length=150)


    # attributes for the easy question
    easy_question = models.TextField(default='')
    easy_answer = models.CharField(max_length=30,default='')
    easy_points = models.PositiveIntegerField(default=0)

    # attributes for the medium question
    medium_question = models.TextField(default='')
    medium_answer = models.CharField(max_length=30,default='')
    medium_points = models.PositiveIntegerField(default=0)

    # attributes for the hard question
    hard_question = models.TextField(default='')
    hard_answer = models.CharField(max_length=30,default='')
    hard_points = models.PositiveIntegerField(default=0)



# a connecton between a user and a subject which controlls the points the student have in the subject
class StudentConnectSubject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)




# every time a student follows a subject, there is a relation between the student and all the exercises in the subject
class StudentConnectExercise(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise_Page, on_delete=models.CASCADE)

    # theese variables controls if the student has answered correct on the questions in the exercise, so the student
    # cant answer correct all the time on the same question and gain infinity points
    completed_easy = models.BooleanField(default=False)
    completed_medium = models.BooleanField(default=False)
    completed_hard = models.BooleanField(default = False)

# ----------------------------------------------------------

# UserProfile is a model with a OneToOneField to User. This let us add fields to the nysil-user, which is importamt
# because users need to have foreign-keys to their subjects

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    #test = models.IntegerField(default=5)
    subjects = models.ManyToManyField(Subject, blank=True)


    def add_subject(self, subject_pk):
        subject = Subject.objects.get(pk=subject_pk)
        student_subject_conn = StudentConnectSubject(user=self.user, subject=subject)
        find_student_subject_conn = StudentConnectSubject.objects.filter(user=self.user,subject=subject).exists()
        if not find_student_subject_conn:
            student_subject_conn.save()

        # create a StudentConnectExercise between the current student and all the exercises in the subject
        for chapter in subject.chapter_set.all():
            for exercise in chapter.exercise_page_set.all():
                connection = StudentConnectExercise(user=self.user, exercise=exercise)
                # checking for a connection between user and exercise that already exists
                find_connection = StudentConnectExercise.objects.filter(user=self.user,exercise=exercise).exists()
                if not find_connection:
                    connection.save()
        already_follows = self.subjects.filter(pk=subject_pk).exists()
        if not already_follows:

            self.subjects.add(Subject.objects.get(pk=subject_pk))


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

# ----------------------------------------------------------


class Comment(models.Model):
    publisher = models.ForeignKey(User)
    published_time = models.DateTimeField(auto_now_add=True, blank=True)
    text = models.TextField()
    chapter = models.ForeignKey(Chapter)
    exercise = models.ForeignKey(Exercise_Page)


    def get_published_time(self):
        return str(self.published_time)[:16]

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import UserForm
from .models import Subject

from django.db.models import Q


# view for the frontpage
def index(req):
    return render(req,'main/header.html')

# method uses to logout a user, an redirects to the frontpage
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))

# method uses to login a user
def login_user(request):
    if request.method == "POST":
        # logic to get the typed in username and password
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
            else:
                return render(request, 'main/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'main/login.html', {'error_message': 'Invalid login'})
    return render(request, 'main/login.html')

# method for register a student
def userregister(request):
    form = UserForm(request.POST or None)
    if form.is_valid(): # form.is_valid() checks that tha form is on the correct format
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        confirm = request.POST['confirm']
        if confirm != password:
            return render(request, 'main/userregister.html',{'form': form, 'error_message': 'Password not equal'}, )
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('main:index'))

    context = {
        "form": form,
    }

    return render(request, 'main/userregister.html', context)

# method for register a professor, almost the same as userregister but the activation_key-input has to be corrext
# so all professors needs the activation_key to be an admin
def professorregister(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        confirm = request.POST['confirm']
        if confirm != password:
            return render(request, 'main/professorregister.html', {'form': form, 'error_message': 'Password not equal'}, )
        key = request.POST['key']
        if key != 'abc12345':
            return render(request, 'main/professorregister.html', {'form':form, 'error_message': 'Invalid activation key'},)
        user.is_staff = True
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    context = {
        "form": form,
    }
    return render(request, 'main/professorregister.html', context)

# method for the search-functionality. Used to search for a subject to follow
def search(request):
    user = request.user

    query = request.GET.get('q')
    if query is not None and query != '' and request.is_ajax():
        subjects = Subject.objects.filter(
            Q(subject_name__icontains=query)|Q(subject_code__icontains=query    )

        )

        # you also can limit the maximum of `posts` here.
        # eg: posts[:50]
        context = {'user': user, 'subjects':subjects}
        return render(request, 'main/search.html',context)
    return render(request, 'main/search.html')

# functionallity for adding a sujbject
def add_subject(request, subject_pk):
    user = request.user
    user.userprofile.add_subject(subject_pk)
    # this response makes sure that user gets redirected to the last visited page after adding a subject
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

main/templates/main/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

main/templates/main/header.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>NYSIL</title>
	<meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/css/customize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'my_subjects/css/customize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'progress/css/customize.css' %}" type="text/css">
    <link rel="shortcut icon" href="{% static 'adminpage/img/n_favicon.png' %}" type="image/x-icon" />

	<meta name="viewport" content="width=device-width, initial-scale=1">


	<!-- Latest compiled and minified CSS --><!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
	integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
	crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
	integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
	crossorigin="anonymous">


	 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
	integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
	crossorigin="anonymous"></script>

	<meta name="viewport" content = "width=device-width, initial-scale=1.0">


    <link rel="stylesheet" href="{% static 'main/css/header.css'%}" type = "text/css"/>

</head>
<!-- Layout til bakgrunnen til nettsiden -->
    <body class="body" style="background-color: #E5E4E2;    ">

<div id="wrapper">


        <!-- Navbar -->
        <br>
	<br>
	<br>
        <nav class="navbar navbar-inverse navbar-fixed-top" >
            <div class="container-fluid">

                <!-- makes navbar to dropdown when the page gets to small
                 + button which takes you to the frontpage -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
				    </button>
                    <a href="{% url 'main:index' %}" class="navbar-brand"><img src="{% static 'main/img/ny_logo.png'%}" style="width:100px;height:27px;margin-top:-4px;margin-left:-3px"></a>
                </div>

                <!-- Navbar items -->
                <div class="collapse navbar-collapse" id="mainNavBar">
                    <ul class="nav navbar-nav">

                        <!-- Dropdown for "my subjects " -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Subjects
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <!-- adds all the student subjects to "My Subjects"-dropown -->
                                {% for subject in user.userprofile.subjects.all %}
                                    <li><a href="{% url 'my_subjects:subject_view' subject.pk %}"> {{ subject.subject_code }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <!-- makes the search-field a login-button if the user is not logged in -->
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'main:login_user' %}">Please log in</a></li>
                        {% else %}
                        <li style="margin-top: 8px">

                            <input id="search-input"  type="text" class="form-control" placeholder="Add subject ..."/>
                            <div id="main-results-search"></div>

                        </li>
                        {% endif %}

                    </ul>

                    <!-- button for login -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Makes the progress-button only visible if the user is logged in -->
                        {% if not user.is_authenticated %}
                        {% else %}

                        <li><a href="{% url 'progress:my_progress' %}"><span class="glyphicon glyphicon-list-alt"></span> Progress</a></li>
                        {% endif %}
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'main:login_user' %}">Login</a></li>
                        <!-- Only staff can access the Adminpage, checks this-->
                        {% elif user.is_staff is True %}
                            <li><a href="{% url 'adminpage:admin_index' %}">Adminpage</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, Prof. {{user}}
                                    <span class="glyphicon glyphicon-option-vertical" style="width:2px;height:2px"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'main:logout_user' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% elif user.is_staff is False %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, {{user}}
                                    <span class="glyphicon glyphicon-option-vertical" style="width:2px;height:2px"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'main:logout_user' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>




                </div>

            </div>
        </nav>
    <!-- Code for our Home-page with information about NYSIL -->
        {% block content %}
            <div class="row" style="padding-top: 40px">
              <div class="col-md-2"></div>
              <div class="col-md-2"></div>
              <div class="col-md-2"></div>
              <div class="col-md-2"></div>
              <div class="col-md-2"></div>
              <div class="col-md-2"></div>
            </div>
            <div class="row" style="padding-top: 10px">
              <div class="col-md-3"></div>
              <div class="col-sm-6">
                        <div class="embed-responsive embed-responsive-16by9" style="height: 360px">

                             <!-- Plays youtube on the webpage and uses the youtube-id. "allowsfuulscreen" allows youtube to play in fullscreen -->
                            <iframe style="border:10px solid #000; border-radius: 20px !important;" class="embed-responsive-item" src="http://www.youtube.com/embed/WOb_l5Ms9oE" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
                        </div>
                    </div>
              <div class="col-md-1" style="margin-left: 40px">
              </div>
              <div class="col-md-2">
              </div>
            </div>

            <div class="row" style="padding-top: 40px">
              <div class="col-md-12" style="text-align: center; font-size: 40px;">
              Some of our subjects:</div>
            </div>
            <div class="row" style="padding-top: 40px">
              <div class="col-md-3"></div>
              <div class="col-md-3">
                <div class="panel panel-default" style="border-radius: 46px; height: 92px; background-color: #0094D0">
                    <img src="{% static 'main/img/calculator.png'%}" style="width: 90px; height: 90px">
                    Maths
                    <div class="panel-body"></div>
                </div>
                <br>
                <div class="panel panel-default" style="border-radius: 46px; height: 92px; background-color: #0094D0";>
                    <img src="{% static 'main/img/graphs.png'%}" style="width: 90px; height: 90px">
                    Statistics
                    <div class="panel-body"></div>
                </div>
              </div>
              <div class="col-md-3">
                <div class="panel panel-default" style="border-radius: 46px; height: 92px; background-color: #0094D0">
                    <img src="{% static 'main/img/vessel.png'%}" style="width: 90px; height: 90px">
                    Chemistry
                    <div class="panel-body"></div>
                </div>
                <br>
                <div class="panel panel-default" style="border-radius: 46px; height: 92px; background-color: #0094D0">
                    <img src="{% static 'main/img/programming.png'%}" style="width: 90px; height: 90px">
                    Programming
                    <div class="panel-body"></div>
                </div>
              </div>
              <div class="col-md-3"></div>
            </div>
            <div class="row" style="padding-top: 50px">
                <div class="col-md-12" style="text-align: center; font-size: 40px" >
                How to use NYSIL:
                </div>
            </div>
            <div class="row" style="padding-top: 50px">
              <div class="col-md-2"></div>
              <div class="col-md-4">
                <img src="{% static 'main/img/login.png'%}" style="width:400px;height:150px;">
              </div>
              <div class="col-md-4">
                Start By Logging In:
                <br>
                  Before you can start using our awesome solution for online learning, you have to log in.
                  This is so you can start customizing you profile and begin the exploration.
              </div>
              <div class="col-md-2"></div>
            </div>
            <div class="row" style="padding-top: 100px">
              <div class="col-md-2"></div>
              <div class="col-md-4">
                Add Your Subjects:
              <br>
                  By adding the subjects to your list, you can easily access them. Use the search
                  bar to find your subjects and add them to "My subjects" by clicking the '+' button.
                  Now you will easily be able to locate your subject, and dig into this world of knowlage.
              </div>
              <div class="col-md-4">
                <img src="{% static 'main/img/choose_subject.png'%}" style="width:400px;height:150px;">
              </div>
              <div class="col-md-2"></div>
            </div>
            <div class="row" style="padding-top: 100px">
              <div class="col-md-2"></div>
              <div class="col-md-4">
                <img src="{% static 'main/img/navigate.png'%}" style="width:400px;height:150px;">
              </div>
              <div class="col-md-4">
                Navigate to Your Desired Subtopic:
                <br>
                Start watching videos on the wanted subtopic by clicking into the chapter and
                  then to the desired task. The videos are relatively short so you get a
                  thorough view on the subtopic. After you have finished watching the video
                  you can test yourself by doing tasks for the video. This will maximize
                  your learning and assure you have understood the topic.
              </div>
              <div class="col-md-2"></div>
            </div>
        {% endblock%}
</div>






<footer id="footer">
    <!-- script that makes it able to search for subjects in the database -->
    <script>
        // Implement realtime search with `keyup` function.
        $('#search-input').keyup(function (event) {
          var query =($('#search-input').val());
          if (query != '' || query != ' ') {
            $.ajax({
               type: 'GET',
               url: '{% url "main:search" %}',
               data: {
                 'csrfmiddlewaretoken': '{{ csrf_token }}',
                 'q': query
               },
               success: function(data) {
                  $('#main-results-search').html(data);
               },
               error: function(data) {
                  console.log(data);
               }
             });
          }
        });
        // Removing the element after search
        // and when user clicked another/outside of this element below.
        $(document).click(function(event) {
          $is_inside = $(event.target).closest('#main-results-search').length;
          if( event.target.id == 'search-input' || $is_inside ) {
            return;
          }else {
            $('#results-search').remove();
          }
        });
  </script>
</footer>

</body>

main/templates/main/logged_in_admin.html
{% extends 'main/header.html' %}

{% block adminok %}
<li><a href="{% url 'adminpage:admin_index' %}">Admin</a></li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{user}}
        <span class="glyphicon glyphicon-menu-down" style="width:2px;height:2px"></span>
    <ul class="dropdown-menu">
        <!-- adds all the subjects to "My Subjects"-dropown -->
        <li><a href="{% url 'main:logout_user' %}">Logout</a></li>
    </ul>
</li>
{% block subjects %}
{% endblock %}

{% endblock %}

main/templates/main/logged_in_user.html
{% extends 'main/header.html' %}

{% block adminok %}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{user}}
    <ul class="dropdown-menu">
        <!-- adds all the subjects to "My Subjects"-dropown -->
        <li><a href="{% url 'main:logout_user' %}">Logout</a></li>
    </ul>
</li>

{% endblock %}

main/templates/main/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
</head>


<body id="bg" style="background-image: url('{% static 'main/img/nysil_logo_stor.png' %}');background-size: 1300px 600px;background-repeat: no-repeat;background-attachment: fixed;background-color:#E5E4E2">
<div style="text-align: center;" class="container-fluid">

    <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                <h2 style="margin-top: 10%; font-size: 40px">Please sign in</h2>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'main:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-10">
                                <input style="padding: 10px 100px 10px 0px; border-radius: 4px" id="id_username" maxlength="30" name="username" type="text" placeholder="Username">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <input style="padding: 10px 100px 10px 0px;margin-left: 0px; border-radius: 4px" id="id_password" maxlength="30" name="password" type="password" placeholder="Password">
                            </div>
                        </div>
                        <div style="padding: 10px 0px 10px 1px" class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button style="padding: 10px 84px 10px 84px; background: #0080FF; border-radius: 4px; font-size: 18px; color: white" type="submit" class="btn btn">Sign in</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? </br>
                    <a href="{% url 'main:userregister' %}">Click here</a> to register as user. </br>
                    <a href="{% url 'main:professorregister' %}">Click here</a> to register as professor.<br>
                    <tr><div><a class="btn btn-xs btn-warning" href="{% url 'main:index' %}">Home</a></div></tr>
                </div>
            </div>
    </div>

</div>
</body>
</html>

main/templates/main/search.html
<ul id="results-search">
  {% for subject in subjects %}
  <li>
      {% if not user.is_authenticated %}
      <a href="{% url 'main:login'%}" style="margin-right:10px"><span class="glyphicon glyphicon-plus-sign"> </span> {{ subject.subject_code }}</a>
      {% else %}
      <a href="{% url 'main:add_subject' subject_pk=subject.pk%}" style="margin-left:-35px"><span class="glyphicon glyphicon-plus-sign"> </span> {{ subject.subject_code }}: {{subject.subject_name}}</a>
      {% endif %}
  </li>
  {% endfor %}
</ul>